[package]
name = "fieldless_enum_tools_internals"
version = "0.1.0"
edition = "2018"
rust-version = "1.36"
repository = "https://github.com/matheuz1210/fieldless-enum-tools"
license = "MIT OR Apache-2.0"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"